services:
  db:
    image: postgres:17-alpine
    container_name: go_rms_pg
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_rms
    volumes:
      - go_rms_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d go_rms"]
      interval: 5s
      timeout: 5s
      retries: 5
    # networks:
    #   - go_rms_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: go_rms_pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5059:80"
    depends_on:
      db:
        condition: service_healthy
    # networks:
    #   - go_rms_network

  redis:
    image: redis:8
    container_name: go_rms_redis
    ports:
      - "6399:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    # networks:
    #   - go_rms_network

  # go:
  #   image: golang:tip-trixie
  #   container_name: go_golang
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: go run main.go
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - go_rms_network

volumes:
  go_rms_pg_data:
  redisdata:

# networks:
#   go_rms_network:
